In [1]:
import pandas as pd
import xml.etree.ElementTree as et
import numpy as np
import sqlite3
pd.options.mode.chained_assignment = None
pd.set_option('display.max_columns', 500)

## get all matches in chronological order

In [2]:
conn = sqlite3.connect("../data/eusoccerdatabase.sqlite")
query = "SELECT id, country_id, league_id, season, date, match_api_id, home_team_api_id, away_team_api_id, home_team_goal, away_team_goal, B365H, B365D, B365A, shoton, shotoff, possession FROM Match ORDER BY date asc"
df = pd.read_sql_query(query, conn)
df = df[np.isfinite(df['B365H'])] # drop rows without odds
df

,id,country_id,league_id,season,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,shoton,shotoff,possession
22,4769,4769,4769,2008/2009,2008-08-09 00:00:00,483129,8583,9830,2,1,2.10,3.10,3.75,None,None,None
23,4770,4769,4769,2008/2009,2008-08-09 00:00:00,483130,9827,7819,2,1,1.57,3.60,6.50,None,None,None
24,4771,4769,4769,2008/2009,2008-08-09 00:00:00,483131,9746,9831,1,0,2.30,3.00,3.40,None,None,None
25,4772,4769,4769,2008/2009,2008-08-09 00:00:00,483132,8682,8689,0,1,2.10,3.10,3.80,None,None,None
26,4774,4769,4769,2008/2009,2008-08-09 00:00:00,483134,9829,9847,1,0,2.40,3.10,3.10,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25959,24491,21518,21518,2015/2016,2016-05-15 00:00:00,2030531,8603,8305,2,1,5.00,3.80,1.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>60</comment><stats...
25960,24492,21518,21518,2015/2016,2016-05-15 00:00:00,2030532,8558,8372,4,2,2.00,3.60,3.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>56</comment><stats...
25961,24495,21518,21518,2015/2016,2016-05-15 00:00:00,2030535,9864,8306,4,1,1.80,3.75,4.50,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>42</comment><stats...
25962,24497,21518,21518,2015/2016,2016-05-15 00:00:00,2030537,8370,8581,3,1,1.33,5.25,9.00,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>53</comment><stats...
25968,4702,1729,1729,2015/2016,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>75</comment><stats...

## Save all matches without XML data in chronological order to csv - missing odds dropped

In [3]:
df_noxml=df.drop(['shoton', 'shotoff', 'possession'], axis=1)
df_noxml.to_csv("../data/matches_all.csv")
df_noxml

,id,country_id,league_id,season,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A
22,4769,4769,4769,2008/2009,2008-08-09 00:00:00,483129,8583,9830,2,1,2.10,3.10,3.75
23,4770,4769,4769,2008/2009,2008-08-09 00:00:00,483130,9827,7819,2,1,1.57,3.60,6.50
24,4771,4769,4769,2008/2009,2008-08-09 00:00:00,483131,9746,9831,1,0,2.30,3.00,3.40
25,4772,4769,4769,2008/2009,2008-08-09 00:00:00,483132,8682,8689,0,1,2.10,3.10,3.80
26,4774,4769,4769,2008/2009,2008-08-09 00:00:00,483134,9829,9847,1,0,2.40,3.10,3.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25959,24491,21518,21518,2015/2016,2016-05-15 00:00:00,2030531,8603,8305,2,1,5.00,3.80,1.70
25960,24492,21518,21518,2015/2016,2016-05-15 00:00:00,2030532,8558,8372,4,2,2.00,3.60,3.70
25961,24495,21518,21518,2015/2016,2016-05-15 00:00:00,2030535,9864,8306,4,1,1.80,3.75,4.50
25962,24497,21518,21518,2015/2016,2016-05-15 00:00:00,2030537,8370,8581,3,1,1.33,5.25,9.00
25968,4702,1729,1729,2015/2016,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25

## calculate shots

In [4]:
df_shots = df.dropna(subset=['shoton', 'shotoff'])
df_shots.set_index('id')

,country_id,league_id,season,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,shoton,shotoff,possession
id,,,,,,,,,,,,,,,
7809,7809,7809,2008/2009,2008-08-15 00:00:00,499317,9823,9790,2,2,1.57,3.80,6.00,<shoton />,<shotoff />,<possession />
1730,1729,1729,2008/2009,2008-08-16 00:00:00,489043,9825,8659,1,0,1.20,6.50,15.00,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>65</comment><event...
1731,1729,1729,2008/2009,2008-08-16 00:00:00,489044,8472,8650,0,1,5.50,3.60,1.67,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>45</comment><event...
1732,1729,1729,2008/2009,2008-08-16 00:00:00,489045,8654,8528,2,1,1.91,3.40,4.20,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>50</comment><event...
1734,1729,1729,2008/2009,2008-08-16 00:00:00,489047,8668,8655,2,3,2.00,3.30,4.00,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>46</comment><event...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24491,21518,21518,2015/2016,2016-05-15 00:00:00,2030531,8603,8305,2,1,5.00,3.80,1.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>60</comment><stats...
24492,21518,21518,2015/2016,2016-05-15 00:00:00,2030532,8558,8372,4,2,2.00,3.60,3.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>56</comment><stats...
24495,21518,21518,2015/2016,2016-05-15 00:00:00,2030535,9864,8306,4,1,1.80,3.75,4.50,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>42</comment><stats...
24497,21518,21518,2015/2016,2016-05-15 00:00:00,2030537,8370,8581,3,1,1.33,5.25,9.00,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>53</comment><stats...
4702,1729,1729,2015/2016,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>75</comment><stats...

In [5]:
home_shoton = []
home_shotoff = []
home_shots = []
home_shots_acc = []

away_shoton = []
away_shotoff = []
away_shots = []
away_shost_acc = []


for index, row in df_shots.iterrows():
    home_id = row['home_team_api_id']
    away_id = row['away_team_api_id']
    home_shoton_counter = 0
    home_shotoff_counter = 0
    home_shot_accuracy = 0.0
    home_shots_total = 0
    away_shoton_counter = 0
    away_shotoff_counter = 0
    away_shot_accuracy = 0.0
    away_shots_total = 0
    shoton_root = et.fromstring(str(row['shoton']))
    shotoff_root = et.fromstring(str(row['shotoff']))
    for val in shoton_root.findall('value'):
        if val.find('team') is not None:
            team_id = int(val.find('team').text)
            if team_id == home_id:
                home_shoton_counter = home_shoton_counter + 1
                home_shots_total = home_shots_total + 1
            elif team_id == away_id:
                away_shoton_counter = away_shoton_counter + 1
                away_shots_total = away_shots_total + 1
        
        
    for val2 in shotoff_root.findall('value'):
        if val2.find('team') is not None:
            team_id = int(val2.find('team').text)
            if team_id == home_id:
                home_shotoff_counter = home_shotoff_counter + 1
                home_shots_total = home_shots_total + 1
            elif team_id == away_id:
                away_shotoff_counter = away_shotoff_counter + 1
                away_shots_total = away_shots_total + 1
    
    if home_shots_total != 0:
        home_shot_accuracy = home_shoton_counter / (home_shoton_counter + home_shotoff_counter)
        
    if away_shots_total != 0:
        away_shot_accuracy = away_shoton_counter / (away_shoton_counter + away_shotoff_counter)
    
#    print('Home_Team_ID: ' + str(home_id) + ' Shoton: ' + str(home_shoton_counter) + ' Shotoff: ' + str(home_shotoff_counter) + ' Shot Accuracy: ' + str(home_shot_accuracy))
#    print('Away_Team_ID: ' + str(away_id) + ' Shoton: ' + str(away_shoton_counter) + ' Shotoff: ' + str(away_shotoff_counter) + ' Shot Accuracy: ' + str(away_shot_accuracy))
 
    home_shoton.append(home_shoton_counter)
    home_shotoff.append(home_shotoff_counter)
    home_shots.append(home_shots_total)
    home_shots_acc.append(home_shot_accuracy)
    
    away_shoton.append(away_shoton_counter)
    away_shotoff.append(away_shotoff_counter)
    away_shots.append(away_shots_total)
    away_shost_acc.append(away_shot_accuracy)

df_shots['home_team_shots'] = home_shots
df_shots['home_team_shots_on_target'] = home_shoton
df_shots['home_team_shots_off_target'] = home_shotoff
df_shots['home_team_shot_accuracy'] = home_shots_acc
    
df_shots['away_team_shots'] = away_shots
df_shots['away_team_shots_on_target'] = away_shoton
df_shots['away_team_shots_off_target'] = away_shotoff
df_shots['away_team_shot_accuracy'] = away_shost_acc

In [6]:
df_shots

,id,country_id,league_id,season,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,shoton,shotoff,possession,home_team_shots,home_team_shots_on_target,home_team_shots_off_target,home_team_shot_accuracy,away_team_shots,away_team_shots_on_target,away_team_shots_off_target,away_team_shot_accuracy
49,7809,7809,7809,2008/2009,2008-08-15 00:00:00,499317,9823,9790,2,2,1.57,3.80,6.00,<shoton />,<shotoff />,<possession />,0,0,0,0.000000,0,0,0,0.000000
58,1730,1729,1729,2008/2009,2008-08-16 00:00:00,489043,9825,8659,1,0,1.20,6.50,15.00,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>65</comment><event...,25,12,13,0.480000,5,2,3,0.400000
59,1731,1729,1729,2008/2009,2008-08-16 00:00:00,489044,8472,8650,0,1,5.50,3.60,1.67,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>45</comment><event...,7,4,3,0.571429,16,11,5,0.687500
60,1732,1729,1729,2008/2009,2008-08-16 00:00:00,489045,8654,8528,2,1,1.91,3.40,4.20,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>50</comment><event...,12,5,7,0.416667,22,7,15,0.318182
61,1734,1729,1729,2008/2009,2008-08-16 00:00:00,489047,8668,8655,2,3,2.00,3.30,4.00,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>46</comment><event...,9,2,7,0.222222,16,8,8,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25959,24491,21518,21518,2015/2016,2016-05-15 00:00:00,2030531,8603,8305,2,1,5.00,3.80,1.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>60</comment><stats...,7,5,2,0.714286,13,6,7,0.461538
25960,24492,21518,21518,2015/2016,2016-05-15 00:00:00,2030532,8558,8372,4,2,2.00,3.60,3.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>56</comment><stats...,6,3,3,0.500000,11,8,3,0.727273
25961,24495,21518,21518,2015/2016,2016-05-15 00:00:00,2030535,9864,8306,4,1,1.80,3.75,4.50,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>42</comment><stats...,9,8,1,0.888889,10,7,3,0.700000
25962,24497,21518,21518,2015/2016,2016-05-15 00:00:00,2030537,8370,8581,3,1,1.33,5.25,9.00,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>53</comment><stats...,16,10,6,0.625000,7,3,4,0.428571
25968,4702,1729,1729,2015/2016,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>75</comment><stats...,9,5,4,0.555556,7,5,2,0.714286

In [7]:
#df_shots=df_shots[df_shots['home_team_shot_accuracy']!=0.0].dropna()
df_shots = df_shots[(df_shots[['home_team_shot_accuracy','away_team_shot_accuracy']] != 0).all(axis=1)]
df_csv=df_shots.drop(columns=['shoton','shotoff','possession'],axis=1)
df_csv

,id,country_id,league_id,season,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,home_team_shots,home_team_shots_on_target,home_team_shots_off_target,home_team_shot_accuracy,away_team_shots,away_team_shots_on_target,away_team_shots_off_target,away_team_shot_accuracy
58,1730,1729,1729,2008/2009,2008-08-16 00:00:00,489043,9825,8659,1,0,1.20,6.50,15.00,25,12,13,0.480000,5,2,3,0.400000
59,1731,1729,1729,2008/2009,2008-08-16 00:00:00,489044,8472,8650,0,1,5.50,3.60,1.67,7,4,3,0.571429,16,11,5,0.687500
60,1732,1729,1729,2008/2009,2008-08-16 00:00:00,489045,8654,8528,2,1,1.91,3.40,4.20,12,5,7,0.416667,22,7,15,0.318182
61,1734,1729,1729,2008/2009,2008-08-16 00:00:00,489047,8668,8655,2,3,2.00,3.30,4.00,9,2,7,0.222222,16,8,8,0.500000
62,1735,1729,1729,2008/2009,2008-08-16 00:00:00,489048,8549,8586,2,1,3.20,3.40,2.25,12,7,5,0.583333,7,2,5,0.285714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25959,24491,21518,21518,2015/2016,2016-05-15 00:00:00,2030531,8603,8305,2,1,5.00,3.80,1.70,7,5,2,0.714286,13,6,7,0.461538
25960,24492,21518,21518,2015/2016,2016-05-15 00:00:00,2030532,8558,8372,4,2,2.00,3.60,3.70,6,3,3,0.500000,11,8,3,0.727273
25961,24495,21518,21518,2015/2016,2016-05-15 00:00:00,2030535,9864,8306,4,1,1.80,3.75,4.50,9,8,1,0.888889,10,7,3,0.700000
25962,24497,21518,21518,2015/2016,2016-05-15 00:00:00,2030537,8370,8581,3,1,1.33,5.25,9.00,16,10,6,0.625000,7,3,4,0.428571
25968,4702,1729,1729,2015/2016,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25,9,5,4,0.555556,7,5,2,0.714286

In [8]:
df_csv.to_csv('../data/matches_all_with_shots.csv')

## calculate shots and possession

In [9]:
df_shots_n_pos = df.dropna(subset=['shoton', 'shotoff', 'possession'])
df_shots_n_pos.set_index('id')

,country_id,league_id,season,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,shoton,shotoff,possession
id,,,,,,,,,,,,,,,
7809,7809,7809,2008/2009,2008-08-15 00:00:00,499317,9823,9790,2,2,1.57,3.80,6.00,<shoton />,<shotoff />,<possession />
1730,1729,1729,2008/2009,2008-08-16 00:00:00,489043,9825,8659,1,0,1.20,6.50,15.00,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>65</comment><event...
1731,1729,1729,2008/2009,2008-08-16 00:00:00,489044,8472,8650,0,1,5.50,3.60,1.67,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>45</comment><event...
1732,1729,1729,2008/2009,2008-08-16 00:00:00,489045,8654,8528,2,1,1.91,3.40,4.20,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>50</comment><event...
1734,1729,1729,2008/2009,2008-08-16 00:00:00,489047,8668,8655,2,3,2.00,3.30,4.00,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>46</comment><event...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24491,21518,21518,2015/2016,2016-05-15 00:00:00,2030531,8603,8305,2,1,5.00,3.80,1.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>60</comment><stats...
24492,21518,21518,2015/2016,2016-05-15 00:00:00,2030532,8558,8372,4,2,2.00,3.60,3.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>56</comment><stats...
24495,21518,21518,2015/2016,2016-05-15 00:00:00,2030535,9864,8306,4,1,1.80,3.75,4.50,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>42</comment><stats...
24497,21518,21518,2015/2016,2016-05-15 00:00:00,2030537,8370,8581,3,1,1.33,5.25,9.00,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>53</comment><stats...
4702,1729,1729,2015/2016,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>75</comment><stats...

In [10]:
home_shoton = []
home_shotoff = []
home_shots = []
home_shots_acc = []
home_possession = []

away_shoton = []
away_shotoff = []
away_shots = []
away_shots_acc = []
away_possession = []


for index, row in df_shots_n_pos.iterrows():
    home_id = row['home_team_api_id']
    away_id = row['away_team_api_id']
    home_shoton_counter = 0
    home_shotoff_counter = 0
    home_shot_accuracy = 0.0
    home_shots_total = 0
    home_ball_possession = 0
    home_ball_possession_count = 0
    away_shoton_counter = 0
    away_shotoff_counter = 0
    away_shot_accuracy = 0.0
    away_shots_total = 0
    away_ball_possession = 0
    away_ball_possession_count = 0
    shoton_root = et.fromstring(str(row['shoton']))
    shotoff_root = et.fromstring(str(row['shotoff']))
    possession_root = et.fromstring(str(row['possession']))
    for val in shoton_root.findall('value'):
        if val.find('team') is not None:
            team_id = int(val.find('team').text)
            if team_id == home_id:
                home_shoton_counter = home_shoton_counter + 1
                home_shots_total = home_shots_total + 1
            elif team_id == away_id:
                away_shoton_counter = away_shoton_counter + 1
                away_shots_total = away_shots_total + 1
        
        
    for val2 in shotoff_root.findall('value'):
        if val2.find('team') is not None:
            team_id = int(val2.find('team').text)
            if team_id == home_id:
                home_shotoff_counter = home_shotoff_counter + 1
                home_shots_total = home_shots_total + 1
            elif team_id == away_id:
                away_shotoff_counter = away_shotoff_counter + 1
                away_shots_total = away_shots_total + 1
                
    for val3 in possession_root.findall('value'):
        if (val3.find('homepos') is not None) and (val3.find('awaypos') is not None):
            home_ball_possession = home_ball_possession + int(val3.find('homepos').text)
            home_ball_possession_count = home_ball_possession_count + 1
            
            away_ball_possession = away_ball_possession + int(val3.find('awaypos').text)
            away_ball_possession_count = away_ball_possession_count + 1
            
    
    if home_shots_total != 0:
        home_shot_accuracy = home_shoton_counter / (home_shoton_counter + home_shotoff_counter)
        
    if away_shots_total != 0:
        away_shot_accuracy = away_shoton_counter / (away_shoton_counter + away_shotoff_counter)
        
    if (home_ball_possession_count != 0) and (away_ball_possession_count != 0):
        home_ball_possession = (home_ball_possession / home_ball_possession_count) / 100 * 90
        away_ball_possession = (away_ball_possession / away_ball_possession_count) /100 * 90
        
#    print('Home Ball Possession: ' + str(home_ball_possession) + ' Away Ball Possession: ' + str(away_ball_possession))
#    print('Home_Team_ID: ' + str(home_id) + ' Shoton: ' + str(home_shoton_counter) + ' Shotoff: ' + str(home_shotoff_counter) + ' Shot Accuracy: ' + str(home_shot_accuracy))
#    print('Away_Team_ID: ' + str(away_id) + ' Shoton: ' + str(away_shoton_counter) + ' Shotoff: ' + str(away_shotoff_counter) + ' Shot Accuracy: ' + str(away_shot_accuracy))
 
    home_shoton.append(home_shoton_counter)
    home_shotoff.append(home_shotoff_counter)
    home_shots.append(home_shots_total)
    home_shots_acc.append(home_shot_accuracy)
    home_possession.append(home_ball_possession)
    
    away_shoton.append(away_shoton_counter)
    away_shotoff.append(away_shotoff_counter)
    away_shots.append(away_shots_total)
    away_shots_acc.append(away_shot_accuracy)
    away_possession.append(away_ball_possession)

df_shots_n_pos['home_team_shots'] = home_shots
df_shots_n_pos['home_team_shots_on_target'] = home_shoton
df_shots_n_pos['home_team_shots_off_target'] = home_shotoff
df_shots_n_pos['home_team_shot_accuracy'] = home_shots_acc
df_shots_n_pos['home_team_possession'] = home_possession
    
df_shots_n_pos['away_team_shots'] = away_shots
df_shots_n_pos['away_team_shots_on_target'] = away_shoton
df_shots_n_pos['away_team_shots_off_target'] = away_shotoff
df_shots_n_pos['away_team_shot_accuracy'] = away_shots_acc
df_shots_n_pos['away_team_possession'] = away_possession

In [11]:
df_shots_n_pos

,id,country_id,league_id,season,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,shoton,shotoff,possession,home_team_shots,home_team_shots_on_target,home_team_shots_off_target,home_team_shot_accuracy,home_possession,away_team_shots,away_team_shots_on_target,away_team_shots_off_target,away_team_shot_accuracy,away_possession
49,7809,7809,7809,2008/2009,2008-08-15 00:00:00,499317,9823,9790,2,2,1.57,3.80,6.00,<shoton />,<shotoff />,<possession />,0,0,0,0.000000,0.000,0,0,0,0.000000,0.000
58,1730,1729,1729,2008/2009,2008-08-16 00:00:00,489043,9825,8659,1,0,1.20,6.50,15.00,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>65</comment><event...,25,12,13,0.480000,57.825,5,2,3,0.400000,32.175
59,1731,1729,1729,2008/2009,2008-08-16 00:00:00,489044,8472,8650,0,1,5.50,3.60,1.67,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>45</comment><event...,7,4,3,0.571429,40.950,16,11,5,0.687500,49.050
60,1732,1729,1729,2008/2009,2008-08-16 00:00:00,489045,8654,8528,2,1,1.91,3.40,4.20,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>50</comment><event...,12,5,7,0.416667,44.775,22,7,15,0.318182,45.225
61,1734,1729,1729,2008/2009,2008-08-16 00:00:00,489047,8668,8655,2,3,2.00,3.30,4.00,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>46</comment><event...,9,2,7,0.222222,46.575,16,8,8,0.500000,43.425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25959,24491,21518,21518,2015/2016,2016-05-15 00:00:00,2030531,8603,8305,2,1,5.00,3.80,1.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>60</comment><stats...,7,5,2,0.714286,52.875,13,6,7,0.461538,37.125
25960,24492,21518,21518,2015/2016,2016-05-15 00:00:00,2030532,8558,8372,4,2,2.00,3.60,3.70,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>56</comment><stats...,6,3,3,0.500000,49.725,11,8,3,0.727273,40.275
25961,24495,21518,21518,2015/2016,2016-05-15 00:00:00,2030535,9864,8306,4,1,1.80,3.75,4.50,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>42</comment><stats...,9,8,1,0.888889,37.800,10,7,3,0.700000,52.200
25962,24497,21518,21518,2015/2016,2016-05-15 00:00:00,2030537,8370,8581,3,1,1.33,5.25,9.00,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>53</comment><stats...,16,10,6,0.625000,46.800,7,3,4,0.428571,43.200
25968,4702,1729,1729,2015/2016,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<possession><value><comment>75</comment><stats...,9,5,4,0.555556,61.965,7,5,2,0.714286,28.035

In [12]:
df_shots_n_pos = df_shots_n_pos[(df_shots_n_pos[['home_team_shot_accuracy','away_team_shot_accuracy']] != 0).all(axis=1)]
df_shots_n_pos = df_shots_n_pos[(df_shots_n_pos[['home_team_possession','away_team_possession']] != 0).all(axis=1)]
df_csv_pos=df_shots_n_pos.drop(columns=['shoton','shotoff', 'possession'],axis=1)
df_csv_pos

,id,country_id,league_id,season,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,home_team_shots,home_team_shots_on_target,home_team_shots_off_target,home_team_shot_accuracy,home_possession,away_team_shots,away_team_shots_on_target,away_team_shots_off_target,away_team_shot_accuracy,away_possession
58,1730,1729,1729,2008/2009,2008-08-16 00:00:00,489043,9825,8659,1,0,1.20,6.50,15.00,25,12,13,0.480000,57.825,5,2,3,0.400000,32.175
59,1731,1729,1729,2008/2009,2008-08-16 00:00:00,489044,8472,8650,0,1,5.50,3.60,1.67,7,4,3,0.571429,40.950,16,11,5,0.687500,49.050
60,1732,1729,1729,2008/2009,2008-08-16 00:00:00,489045,8654,8528,2,1,1.91,3.40,4.20,12,5,7,0.416667,44.775,22,7,15,0.318182,45.225
61,1734,1729,1729,2008/2009,2008-08-16 00:00:00,489047,8668,8655,2,3,2.00,3.30,4.00,9,2,7,0.222222,46.575,16,8,8,0.500000,43.425
62,1735,1729,1729,2008/2009,2008-08-16 00:00:00,489048,8549,8586,2,1,3.20,3.40,2.25,12,7,5,0.583333,45.900,7,2,5,0.285714,44.100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25959,24491,21518,21518,2015/2016,2016-05-15 00:00:00,2030531,8603,8305,2,1,5.00,3.80,1.70,7,5,2,0.714286,52.875,13,6,7,0.461538,37.125
25960,24492,21518,21518,2015/2016,2016-05-15 00:00:00,2030532,8558,8372,4,2,2.00,3.60,3.70,6,3,3,0.500000,49.725,11,8,3,0.727273,40.275
25961,24495,21518,21518,2015/2016,2016-05-15 00:00:00,2030535,9864,8306,4,1,1.80,3.75,4.50,9,8,1,0.888889,37.800,10,7,3,0.700000,52.200
25962,24497,21518,21518,2015/2016,2016-05-15 00:00:00,2030537,8370,8581,3,1,1.33,5.25,9.00,16,10,6,0.625000,46.800,7,3,4,0.428571,43.200
25968,4702,1729,1729,2015/2016,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25,9,5,4,0.555556,61.965,7,5,2,0.714286,28.035

In [13]:
df_csv_pos.to_csv('../data/matches_all_with_shots_and_possession.csv')